services:
  m3u8-harvester:
    image: ghcr.io/hpyer/m3u8-harvester:latest
    container_name: m3u8-harvester
    ports:
      - "6868:6868"
    volumes:
      - ./storage:/app/storage
    environment:
      - RUST_LOG=info
      - DATABASE_URL=sqlite:/app/storage/db/app.db?mode=rwc
    restart: unless-stopped
